In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
spiele = pd.read_csv("vg_sales.csv")
spiele.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

In [13]:
spiele_neu = spiele[['Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']]
spiele_neu = spiele_neu.sample(frac=1).reset_index(drop=True)

## Data Scientist beim Retro Gamer Magazine

Sie arbeiten als Data Scientist f√ºr die Videospiele-Zeitschrift "Retro Gamer Magazine" und sollen helfen Erkenntnisse aus einem Datensatz zu gewinnen. Sie setzen sich an Ihren Arbeitsplatz, schalten den Computer an und nach einiger Zeit landen Sie in einem Ordner, der eine Datei mit dem Namen "vs_sales.csv" beinhaltet. Laden Sie diese Datei in ein Pandas Dataframe und geben Sie die ersten 10 Zeilen aus und schauen Sie sich diese erst mal in Ruhe an.

In [14]:
spiele_neu.head(10)

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales
0,Shin Koihime Musou: Otome Ryouran * Sangokushi...,PSP,2010.0,Adventure,Yeti,0.00,0.00,0.03,0.00
1,Tribes: Aerial Assault,PS2,NaN,Shooter,Unknown,0.11,0.09,0.00,0.03
2,Super Mario Bros. 3,GBA,2003.0,Platform,Nintendo,2.93,1.25,0.83,0.20
3,NBA 2K11,PS3,2010.0,Action,Take-Two Interactive,1.41,0.21,0.03,0.16
4,Winx Club: Saving Alfea,3DS,2014.0,Action,Namco Bandai Games,0.00,0.01,0.00,0.00
5,The Smurfs,PS,1998.0,Action,Infogrames,0.02,0.02,0.00,0.00
6,Future Tactics: The Uprising,XB,2004.0,Strategy,JoWood Productions,0.02,0.01,0.00,0.00
7,Untold Legends: Dark Kingdom,PS3,2006.0,Role-Playing,Electronic Arts,0.14,0.02,0.02,0.02
8,WWE All Stars,3DS,2011.0,Fighting,THQ,0.15,0.06,0.00,0.02
9,Mario Paint,SNES,1992.0,Misc,Nintendo,1.43,0.54,0.71,0.07

Einige Spalten sind selbsterkl√§rend. Bei anderen wissen Sie aber nicht genau was damit gemeint ist. Als erfahrener Data Scientist wissen Sie nat√ºrlich was in so einem Fall zu tun ist... Sie fragen einfach nach! Sie holen Ihren Chef zu sich und zeigen ihm mit fragenden Blick nach den Spalten "NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales". Er erkl√§rt ihnen daraufhin, dass es sich jeweils um die Verkaufszahlen in Millionen handelt, entsprechend in Nordamerika, Europa, Japan und dem Rest der Welt. Nun ist alles klar und Sie k√∂nnen anfangen den Datensatz zu analysieren und zu bearbeiten!

M√∂gliche Fragen:
1. Was sind die beliebtesten Spiele in NA/EU/JP. Gibt es √úberschneidungen/Unterschiede? Welche Gr√ºnde k√∂nnte es daf√ºr geben?
2. Zu welchen Genres wurden die meisten/wenigsten Spiele produziert?
3. In welchen Jahren wurden die meisten/wenigsten Spiele produziert?
4. Welche Publisher produzierte die meisten Spiele?
5. F√ºgen Sie eine weitere Spalte mit dem Namen "Global_Sales" ein, die die Sales aller anderen Spalten aufsummiert.
6. Erstellen Sie ein Ranking mit den TOP 20 der meist verkauftesten Spiele mit den Spalten: "Ranking", "Name", "Year", "Genre" und "Publisher". 
7. Vergleichen Sie die bisherigen Erkenntnisse mit dem was Sie im Internet recherchieren k√∂nnen.
8. √úberlegen Sie sich weitere Fragen zu dem Datensatz.
9. Entfernen Sie alle Zeilen die NaN enthalten und deren Publisher Unknown sind.

Take away: 
- Sortieren 
- Aggregate 
- Datenbereinigung
- Matplotlib/Seaborn
- Spalten entfernen/einf√ºgen
- List Comprehension/zip